### ISSUE TITLE
gnus + golden-ratio-mode don't play well

### ISSUE THREAD

**Issue by algernon** [algernon/emacs.d#4]
When launching gnus, golden-ratio-mode should be turned off, and when quitting, it should be turned back on. Perhaps it should be turned off locally for Gnus buffers only? Not sure if that'd work.

In general, though, global on/off would work, because I don't leave gnus running when I switch to other tasks for longer times.

**Comment by Ganneff** [comment]
Silly you, just read its code

   (setq golden-ratio-exclude-modes '("calendar-mode" "gnus-summary-mode"
                                       "gnus-article-mode" "calc-mode" "calc-trail-mode"
                                       "bbdb-mode"))

**Comment by algernon** [comment]
Whee! Thanks!
